# Generated by Django 5.1.6 on 2025-05-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('manager', models.CharField(max_length=200, verbose_name='Руководитель клуба')),
                ('about', models.TextField(verbose_name='Описание')),
                ('students', models.IntegerField(verbose_name='Количество занимающихся')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('main_address', models.CharField(max_length=300, verbose_name='Адрес главного зала')),
                ('image', models.ImageField(upload_to='club', verbose_name='Лого клуба')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Сайт')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('about', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Текст')),
                ('banner', models.ImageField(upload_to='post_image', verbose_name='Баннер записи')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Дата редактирования')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('mid_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('about', models.CharField(max_length=300, verbose_name='Описание')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('ava', models.ImageField(upload_to='staff', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('trainer', models.CharField(max_length=200, verbose_name='Главный тренер')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.club', verbose_name='Клуб')),
            ],
        ),
    ]
