# Generated by Django 5.2.1 on 2025-05-20 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_club_slug_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Slug может содержать только буквы, цифры, дефисы и подчёркивания.', regex='^[-\\w\\u0400-\\u04FF]+$')]),
        ),
    ]
